Script started on Thu 09 Feb 2012 04:08:05 PM PST
bash-3.2$ valgrind malloc
==3925== Memcheck, a memory error detector
==3925== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==3925== Using Valgrind-3.5.0 and LibVEX; rerun with -h for copyright info
==3925== Command: malloc
==3925== 
0x4c30090-> {6, (nil)}
==3925== 
==3925== HEAP SUMMARY:
==3925==     in use at exit: 16 bytes in 1 blocks
==3925==   total heap usage: 2 allocs, 1 frees, 32 bytes allocated
==3925== 
==3925== LEAK SUMMARY:
==3925==    definitely lost: 16 bytes in 1 blocks
==3925==    indirectly lost: 0 bytes in 0 blocks
==3925==      possibly lost: 0 bytes in 0 blocks
==3925==    still reachable: 0 bytes in 0 blocks
==3925==         suppressed: 0 bytes in 0 blocks
==3925== Rerun with --leak-check=full to see details of leaked memory
==3925== 
==3925== For counts of detected and suppressed errors, rerun with: -v
==3925== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)
bash-3.2$ dtb [K[K[K[Kgdb malloc
GNU gdb (GDB) Red Hat Enterprise Linux (7.0.1-23.el5_5.2)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/l/easimmon/private/cs12b/lab5/code/malloc...done.
(gdb) break main
Breakpoint 1 at 0x400567: file malloc.c, line 13.
(gdb) run
Starting program: /afs/cats.ucsc.edu/users/l/easimmon/private/cs12b/lab5/code/malloc 

Breakpoint 1, main (argc=1, argv=0x7fffffffe5a8) at malloc.c:13
13	   node_ref ptr = malloc (sizeof (struct node));
(gdb) print ptr
$1 = (node_ref) 0x0
(gdb) print *pr[Ktr
Cannot access memory at address 0x0
(gdb) step
14	   ptr = malloc (sizeof (struct node));
(gdb) print pts[Kr
$2 = (node_ref) 0x601010
(gdb) print *pts[Kr
$3 = {value = 0, link = 0x0}
(gdb) step
15	   ptr->value = 6;
(gdb) step
16	   ptr->link = NULL;
(gdb) step
17	   printf ("%p-> {%d, %p}\n", ptr, ptr->value, ptr->link);
(gdb) print pt[Ktr
$4 = (node_ref) 0x601030
(gdb) print pts[Kr*
A syntax error in expression, near `'.
(gdb) print*p[K[K *pts[Kr
$5 = {value = 6, link = 0x0}
(gdb) step
0x601030-> {6, (nil)}
18	   free (ptr);
(gdb) step
19	   return EXIT_SUCCESS;
(gdb) step
20	}
(gdb) step
0x0000003bd5e1d994 in __libc_start_main () from /lib64/libc.so.6
(gdb) quit
A debugging session is active.

	Inferior 1 [process 4031] will be killed.

Quit anyway? (y or n) y
bash-3.2$ exit
exit

Script done on Thu 09 Feb 2012 04:15:15 PM PST
